apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  template:
    spec:
      containers:
      - name: node-exporter
        volumeMounts:
        - mountPath: /srv/txt_collector
          name: textfile-dir
          readOnly: false
      volumes:
      - name: textfile-dir
        hostPath:
          path: /var/lib/node-exporter
