apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  retention: 1w
  externalUrl: https://prometheus.$(DOMAIN)/
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 10Gi

