---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    use: "codimd-postgres"
  name: "codimd-postgres"
  namespace: "hackmd"
spec:
  storageClassName: "rook-ceph-block"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"
