kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tmp-data
  namespace: sshd
spec:
  storageClassName: "iscsi-targetd-vg-targetd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

