{
 "title": "Kubernetes Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "role", "query": "worker,backup,master" }
  ]
 },
 "panels": [
  { "title": "[[role]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "role" },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    rate( node_cpu_seconds_total{mode!=\"idle\"}[5m] ) * on (instance) group_left(label_role)\n        max by (instance,label_role) (\n            label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n        )\n) / sum (machine_cpu_cores{role=\"[[role]]\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - sum(\n    node_memory_MemAvailable_bytes * on (instance) group_left(label_role)\n        max by (instance,label_role) (\n            label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n        )\n) / sum (machine_memory_bytes{role=\"[[role]]\"})) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate( node_network_receive_bytes_total[5m] ) * on (instance) group_left(label_role)\n    max by (instance,label_role) (\n        label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n    ))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate( node_network_transmit_bytes_total[5m] ) * on (instance) group_left(label_role)\n    max by (instance,label_role) (\n        label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n    ))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "[[role]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    rate( node_cpu_seconds_total{mode!=\"idle\"}[5m] ) * on (instance) group_left(label_role)\n        max by (instance,label_role) (\n            label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n        )\n) / sum (machine_cpu_cores{role=\"[[role]]\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - sum(\n    node_memory_MemAvailable_bytes * on (instance) group_left(label_role)\n        max by (instance,label_role) (\n            label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n        )\n) / sum (machine_memory_bytes{role=\"[[role]]\"})) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate( node_network_receive_bytes_total[5m] ) * on (instance) group_left(label_role)\n    max by (instance,label_role) (\n        label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n    ))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate( node_network_transmit_bytes_total[5m] ) * on (instance) group_left(label_role)\n    max by (instance,label_role) (\n        label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n    ))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "[[role]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_labels{label_role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{role=\"[[role]]\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    rate( node_cpu_seconds_total{mode!=\"idle\"}[5m] ) * on (instance) group_left(label_role)\n        max by (instance,label_role) (\n            label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n        )\n) / sum (machine_cpu_cores{role=\"[[role]]\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - sum(\n    node_memory_MemAvailable_bytes * on (instance) group_left(label_role)\n        max by (instance,label_role) (\n            label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n        )\n) / sum (machine_memory_bytes{role=\"[[role]]\"})) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate( node_network_receive_bytes_total[5m] ) * on (instance) group_left(label_role)\n    max by (instance,label_role) (\n        label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n    ))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate( node_network_transmit_bytes_total[5m] ) * on (instance) group_left(label_role)\n    max by (instance,label_role) (\n        label_replace(kube_node_labels{label_role=\"[[role]]\"}, \"instance\",\"$1\",\"node\",\"(.*)\")\n    ))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_info) by (os_image, kubelet_version)",
     "legendFormat": "k8s {{kubelet_version}} / {{os_image}}"
    }
   ]
  },
  {
   "title": "Pods by phase",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {}
   ]
  },
  {
   "title": "Pods by namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Top 5 Pod CPU Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sort(topk(5, sum (rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"\", pod!=\"\"}[5m])) by (pod_name, namespace))) "
    }
   ]
  },
  {
   "title": "Top 5 Pod Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sort(topk(5, sum (container_memory_working_set_bytes{image!=\"\", container!=\"\", pod!=\"\"}) by (pod_name, namespace)))"
    }
   ]
  }
 ]
}