resources:
- base/
- grafana-base/
- resources/k8s.yaml
- resources/ingress.yaml
- resources/pvc.yaml
- resources/prometheus-additional.yaml
- resources/smart-mon-exporter.yaml
- resources/zfs-exporter.yaml

configMapGenerator:
- name: kp-config
  namespace: monitoring
  literals:
  - DOMAIN=example.com

vars:
- name: DOMAIN
  objref:
    kind: ConfigMap
    name: kp-config
    namespace: monitoring
    apiVersion: v1
  fieldref:
    fieldpath: data.DOMAIN
configurations:
- varReference.yaml

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: node-exporter
    namespace: monitoring
  path: patches/node-exporter.json.yaml

patchesStrategicMerge:
- patches/prometheus.yaml
- patches/alertmanager.yaml
- patches/grafana.yaml
- patches/node-exporter.yaml
