apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  externalUrl: https://prometheus.$(DOMAIN)/
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
