apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-manager
  namespace: longhorn-system
spec:
  template:
    spec:
      volumes:
      - name: longhorn
        hostPath:
          path: /tank/longhorn/
