---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfsd
  labels:
    app: nfsd
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  loadBalancerIP: "192.168.1.212"
  type: "LoadBalancer"
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfsd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfsd
  labels:
    app: nfsd
spec:
  selector:
    matchLabels:
      app: nfsd
  template:
    metadata:
      labels:
        app: nfsd
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      serviceAccountName: nfsd
      containers:
      - name: nfsd
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        resources:
          requests:
            memory: "256Mi"
          limits:
            cpu: 500m
            memory: "1024Mi"
        securityContext:
          privileged: true
          # capabilities:
          #   add: ["SYS_ADMIN", "SETPCAP"]
        volumeMounts:
        - name: export
          mountPath: /exports
      volumes:
        - name: export
          persistentVolumeClaim:
            claimName: nfsd-ceph
