---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    use: "codimd"
  name: codimd
spec:
  capacity:
    storage: "10Gi"
  accessModes:
  - ReadWriteMany
  nfs:
    path: /codimd/files
    server: $(NFS_SERVER)
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    use: "codimd"
  name: codimd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchLabels:
      use: "codimd"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    use: "codimd-backup"
  name: codimd-backup
spec:
  capacity:
    storage: "10Gi"
  accessModes:
  - ReadWriteMany
  nfs:
    path: /codimd/backup
    server: $(NFS_SERVER)
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    use: "codimd"
  name: codimd-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchLabels:
      use: "codimd-backup"
