commonLabels:
  app: nginx-ingress
namespace: ingress
resources:
- src.yaml
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ing-ingress-nginx-controller
    namespace: ingress
  data:
    keep-alive-requests: "10000"
    upstream-keepalive-connections: "200"
    max-worker-connections: "65536"
