commonLabels:
  app: nginx-ingress
namespace: ingress
resources:
- src.yaml
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ing-ingress-nginx-controller
    namespace: ingress
  data:
    keep-alive-requests: "10000"
    upstream-keepalive-connections: "200"
    max-worker-connections: "65536"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ing-ingress-nginx-controller
    namespace: ingress
  spec:
    template:
      spec:
        containers:
        - name: controller
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 512Mi
