---
controller:
  kind: Deployment
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.200"
  stats:
    enabled: true
  replicaCount: 3

  # autoscaling:
  #   enabled: true
  #   minReplicas: 2
  # config:
  #   proxy-real-ip-cidr: "192.168.1.0/24"
  image:
    repository: "asia.gcr.io/k8s-artifacts-prod/ingress-nginx/controller"

  extraArgs:
    enable-ssl-passthrough:

  resources:
   limits:
     cpu: 300m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 64Mi

  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

defaultBackend:
  resources:
    limits:
      cpu: 50m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi

rbac:
  create: true

podSecurityPolicy:
  enabled: true
