---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "200Gi"
  storageClassName: silver
  volumeMode: Filesystem
