---
kind: Service
apiVersion: v1
metadata:
  name: h
  labels:
    app: nfs
    component: h
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv4
  - IPv6
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs
    component: h
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h
  labels:
    app: nfs
    component: h
spec:
  selector:
    matchLabels:
      app: nfs
      component: h
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs
        component: h
    spec:
      serviceAccountName: shared
      containers:
      - name: nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        args:
        - "/h"
        - "/cg"
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        resources:
          requests:
            cpu: 50m
            memory: "256Mi"
          limits:
            cpu: 500m
            memory: "1024Mi"
        securityContext:
          privileged: true
          # capabilities:
          #   add: ["SYS_ADMIN", "SETPCAP"]
        volumeMounts:
        - name: h
          mountPath: /h
      volumes:
        - name: h
          persistentVolumeClaim:
            claimName: h
