---
kind: Namespace
apiVersion: v1
metadata:
  name: chrome
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chrome
  name: chrome
  namespace: chrome
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: chrome
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chrome
  name: chrome
  namespace: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chrome
    spec:
      securityContext:
        fsGroup: 50
      containers:
      - image: browserless/chrome:latest
        imagePullPolicy: IfNotPresent
        name: chrome
        ports:
        - name: chrome
          containerPort: 3000
        env:
        - name: ENABLE_CORS
          value: 'true'
        - name: DEFAULT_STEALTH
          value: 'true'
        # volumeMounts:
        # - name: tmp-data
        #   mountPath: /home/dev/tmp
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      # volumes:
      # - name: tmp-data
      #   persistentVolumeClaim:
      #     claimName: tmp-data
