---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sites-backup
spec:
  schedule: "53 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: ghcr.io/yuanying/docker-sshd:0.2.2
            imagePullPolicy: IfNotPresent
            command:
            - sudo
            - rsync
            - -avz
            - --delete
            - /original/
            - /backup/
            volumeMounts:
            - name: original
              mountPath: /original
            - name: backup
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: original
            nfs:
              path: /sites
              server: sites.fs.svc.cluster.local
          - name: backup
            nfs:
              path: /sites
              server: 192.168.1.121

