---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfsd
  labels:
    app: nfsd
---
kind: Service
apiVersion: v1
metadata:
  name: nfs
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfsd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfsd
  labels:
    app: nfsd
spec:
  selector:
    matchLabels:
      app: nfsd
  template:
    metadata:
      labels:
        app: nfsd
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
        dedicated: nfs
      tolerations:
      - operator: Equal
        effect: NoSchedule
        key: tgtd.unstable.cloud/storage
      - operator: Equal
        effect: NoSchedule
        key: dedicated
        value: nfs
      serviceAccountName: nfsd
      containers:
      - name: nfsd
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        resources:
          requests:
            memory: "256Mi"
          limits:
            cpu: 500m
            memory: "1024Mi"
        securityContext:
          privileged: true
          # capabilities:
          #   add: ["SYS_ADMIN", "SETPCAP"]
        volumeMounts:
        - name: export
          mountPath: /exports
      volumes:
        - name: export
          hostPath:
            path: /export
