config:
  LEGO_EMAIL: yuan-lego@fraction.jp
  LEGO_URL: https://acme-v01.api.letsencrypt.org/directory

rbac:
  create: true

resources:
  limits:
    cpu: 40m
    memory: 128Mi
  requests:
    cpu: 40m
    memory: 64Mi
