---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

