---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bds
spec:
  template:
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: main
        tty: true
        stdin: true
