---
apiVersion: v1
kind: Service
metadata:
  name: mail
  labels:
    app: mail
spec:
  type: LoadBalancer
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 2405:6581:8580:301:face:b00c:888:888
  externalTrafficPolicy: Local
  ports:
  - port: 25
    name: transfer
    targetPort: transfer
    protocol: TCP
  - name: esmtp-implicit
    port: 465
    targetPort: esmtp-implicit
    protocol: TCP
  - port: 587
    name: esmtp-explicit
    targetPort: esmtp-explicit
    protocol: TCP
  - port: 993
    name: imap-implicit
    targetPort: imap-implicit
    protocol: TCP
  selector:
    app: mail
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
  labels:
    app: mail
spec:
  selector:
    matchLabels:
      app: mail
  replicas: 1
  template:
    metadata:
      labels:
        app: mail
    spec:
      hostName: mail
      terminationGracePeriodSeconds: 60
      containers:
      - name: mail
        image: ghcr.io/docker-mailserver/docker-mailserver:10.5.0
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
          privileged: false
          capabilities:
            add:
              # file permission capabilities
              - CHOWN
              - FOWNER
              - MKNOD
              - SETGID
              - SETUID
              - DAC_OVERRIDE
              # network capabilities
              - NET_ADMIN  # needed for F2B
              - NET_RAW    # needed for F2B
              - NET_BIND_SERVICE
              # miscellaneous  capabilities
              - SYS_CHROOT
              - SYS_PTRACE
              - KILL
            drop: [ALL]
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 25
          name: smtp
        - containerPort: 465
          name: esmtp-implicit
        - containerPort: 587
          name: esmtp-explicit
        - containerPort: 993
          name: imap-implicit
        envFrom:
        - configMapRef:
            name: env
        volumeMounts:
        - name: tls
          mountPath: /etc/ssl/mail
          readOnly: true
        - name: postfix
          mountPath: /tmp/docker-mailserver/
          readOnly: true
        - name: dkim
          mountPath: /tmp/docker-mailserver/opemdkim
          readOnly: true
        - name: accounts
          mountPath: /tmp/docker-mailserver/postfix-accounts.cf
          subPath: postfix-accounts.cf
          readOnly: true
        - name: dkim-keys
          mountPath: /tmp/docker-mailserver/opendkim/keys
          readOnly: true
        - name: data
          mountPath: /var/mail
          subPath: mail
        - name: data
          mountPath: /var/mail-state
          subPath: mail-state
        resources:
          requests:
            memory: 512Mi
      volumes:
      - name: postfix
        configMap:
          name: postfix
      - name: dkim
        configMap:
          name: dkim
      - name: accounts
        secret:
          secretName: accounts
      - name: dkim-keys
        secret:
          secretName: dkim
      - name: tls
        secret:
          secretName: mail-tls
      - name: data
        nfs:
          path: /mail
          server: mail.fs.svc.cluster.local
