commonLabels:
  app: cert-manager
resources:
- cert-manager.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
  path: patch.json
