kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: "iscsi-targetd-vg-targetd"
spec:
  storageClassName: "iscsi-targetd-vg-targetd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
